### ISSUE TITLE
"继续阅读"文字错位

### ISSUE THREAD

**Issue by ghost** [manyang901/material#10]
![screenshot_20180212_221931](https://user-images.githubusercontent.com/24886463/36100935-df89e5b0-1042-11e8-8b5c-1d29546c8623.png)
似乎文字一多就会错位
https://blog.kucloud.win 往下滑一下就看到了, Chrome 66
顺便一说sidebar比例貌似有点奇怪 有大有小
链接下划线特效强烈好评

**Comment by eastonman** [comment]
嗯浮动没有清除
