### ISSUE TITLE
反馈一些小问题

### ISSUE THREAD

**Issue by 493Arceus** [manyang901/material#14]
1. 不知道怎么莫名其妙的就不显示文章内容了，点进去是空的
2.与Pio插件不兼容，希望可以适配一下(可能被覆盖掉了)

**Comment by eastonman** [comment]
能否提供一个演示呢？
比如你的blog之类的

**Comment by 493Arceus** [comment]
blog.superuser.app

**Comment by eastonman** [comment]
```

<div class="mdui-card-content mdui-typo">
								<div id="md_content_5" class="md_content" style="min-height: 50px;">
<textarea id="append-test" style="display:none">
***********************This is test page
</textarea>
</div>	 

```
style="display: none;"导致了不显示
其中的`<div>`和`<textarea>`不属于我的代码
你检查一下你的插件

**Comment by 493Arceus** [comment]
emmm非常感谢您的帮助，已经找到了问题，是由[Markdown 编辑器 Editor.md for Typecho](https://github.com/pandao/editor.md)这个插件引起的，禁用掉就好了
