### ISSUE TITLE
文章图片显示的问题

### ISSUE THREAD

**Issue by Subilan** [manyang901/material#18]
![qq20180624-101304](https://user-images.githubusercontent.com/36447840/41815235-4435bc62-7797-11e8-8d0b-f1d27f3a26c5.png)

### 出现的问题
所有文章头图错误显示，仅显示「ThumbNail」或者诸如「main-pic」「main-logo」等字样（如图）
从2.1.0就存在很久以前发的博客，文章封面都显示的是「ThumbNail」字样的问题，我在后台已经设置了「只显示随机图片」，然而依然是裂图。

### 希望得到的结果
头图正确显示，并且修复以往的文章这些情况。如有需要，可以访问 https://subilan.win/ 实地考察。

**Comment by Subilan** [comment]
刚才鼓捣了一下，发现如果在后台打开「显示主页的欢迎图」就会出现如图一样的错误，不打开那么就可以显示正常的头图了。~~其实我很想要欢迎图的~~

**Comment by eastonman** [comment]
请问您使用的浏览器是什么呢

**Comment by Subilan** [comment]
很抱歉这么久才回复，是 Chrome Mac 版，_疑似是最新版本的样子。_

**Comment by eastonman** [comment]
请问您能否短暂地在您的网站复现一下问题呢？
十分感谢！

**Comment by eastonman** [comment]
我在我的测试服务器上无法复现问题，您能否仔细描述您的配置或者提供一个演示呢？
谢谢。

**Comment by Subilan** [comment]
刚才去试了一下，居然真的正常显示了！所以之前那一次又是怎么回事……
很抱歉麻烦您了这么长时间，谢谢您的答复！（_这也是提醒各位要仔细测试再发 Issue 啊…_）
