### ISSUE TITLE
页面异常

### ISSUE THREAD

**Issue by NICHX** [manyang901/material#19]
怀疑是JS引用出问题，麻烦作者检查一下

**Comment by eastonman** [comment]
bootcdn几天前突然停止服务
我会尽快更改

**Comment by eastonman** [comment]
bootcdn已301跳转至cdnjs
理论上不存在问题
请问您是否能提供详细信息或演示呢

**Comment by NICHX** [comment]
模板里部分引用js和css的地址已经失效了，手动更换之后页面才正常。演示页面也是相同的异常
https://cdnjs.cloudflare.com/ajax/libs/mdui/0.4.1/css/mdui.min.css

**Comment by NICHX** [comment]
![qq 20181004195803](https://user-images.githubusercontent.com/24547848/46472641-6c7d8f00-c810-11e8-805f-ea35b81b6a62.png)

**Comment by eastonman** [comment]
bootcdn已经做了301跳转，应该是你本地dns缓存问题。
不过我会尽快更改

**Comment by NICHX** [comment]
这样啊，十分感谢
