### ISSUE TITLE
ERROR: Version File Not Writable! UpdateChecker Will NOT Work.

### ISSUE THREAD

**Issue by ykla** [manyang901/material#21]
启用插件提示 ERROR: Version File Not Writable! UpdateChecker Will NOT Work.
但是已经755网站目录了。

**Comment by ykla** [comment]
这句话在网站浏览中也会出现，不止是后台：  freebsdxs.cn

**Comment by ykla** [comment]
777 插件权限后没有问题。

**Comment by eastonman** [comment]
你是否开启了opcahe缓存
主题不会读写插件目录
