### ISSUE TITLE
页脚有4px的空缺

### ISSUE THREAD

**Issue by ghost** [manyang901/material#7]
![screenshot_20180127_193057](https://user-images.githubusercontent.com/24886463/35471575-b23b602c-0398-11e8-8fbc-32804374ad40.png)

**Comment by eastonman** [comment]
这本应是底栏
我检查一下

**Comment by eastonman** [comment]
你有没有demo

**Comment by eastonman** [comment]
麻烦告诉一下版本号
还有设备分辨率

**Comment by ghost** [comment]
网站: https://wska.mainstars.net
Typecho 1.1稳定版
电脑和手机都有这个情况, 电脑1920*1080 手机1440*2560

**Comment by ghost** [comment]
我这里看你的Blog也是有这个问题的
只不过背景颜色浅所以不太明显

**Comment by ghost** [comment]
顺便一说, 分类和归档页面bug也不少
比如https://blog.kucloud.win/category/tech/
sidebar和fab都不会移动

**Comment by eastonman** [comment]
哦这个是遗留问题
前作者留下了很多bug
我接手时间不长，css里面的样式不是很熟悉
不过会修的

**Comment by eastonman** [comment]
遗留bug太多，原作者的库很旧了
我正在彻底重构代码

**Comment by eastonman** [comment]
新版修复了
