### ISSUE TITLE
你好，一个提醒

### ISSUE THREAD

**Issue by xtlsoft** [manyang901/material#9]
（懒得用英文发了）
黎明大佬也有一个viosey主题的后继版本，相较于本版本来说，改动更大一些。
他的github：@idawnlight https://github.com/idawnlight

**Comment by idawnlight** [comment]
这个版本的改动更大，明显比我专业多了_(:3」∠)_

**Comment by eastonman** [comment]
这个我知道。
本身改这个主题出发点在于自用吧，自己加一些功能比较方便。
我换了一个md框架重构，我感觉新的更符合Material Design 的规范，但是彻底重构的话，也不大好发pr，到处都是conflict。
大概就先写着吧

**Comment by eastonman** [comment]
@idawnlight 哇惊动大佬

**Comment by eastonman** [comment]
什么嘛，我连css都不怎么会写，哪里专业了

**Comment by xtlsoft** [comment]
（其实我们也不太会css等）

**Comment by eastonman** [comment]
哦我的博客演示有一些出入，还是旧的
重构完的功能差的太多，没敢用
旧的你可以看deprecated分支
